wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.12
    start_time: 1673431435.735423
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.12
      5: 0.13.7
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 15
lr:
  desc: null
  value: 0.09593954987195448
