wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1673442505.458866
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 23
      - 37
      4: 3.9.7
      5: 0.13.7
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.6
epochs:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.055239055255147045
optimizer:
  desc: null
  value: sgd
